// Pure data — no React imports required

export const SOURCES = [
  {
    name: 'PubMed',
    detail: 'NCBI E-utilities · MeSH',
    color: '#dc2626',
    gradient: 'linear-gradient(135deg,#dc2626,#ea580c)',
    iconKey: 'book',
  },
  {
    name: 'OpenAlex',
    detail: '250 M+ open papers',
    color: '#2563eb',
    gradient: 'linear-gradient(135deg,#2563eb,#0891b2)',
    iconKey: 'db',
  },
  {
    name: 'ClinicalTrials.gov',
    detail: 'v2 · recruiting + active',
    color: '#059669',
    gradient: 'linear-gradient(135deg,#059669,#0d9488)',
    iconKey: 'activity',
  },
];

export const RANKERS = [
  {
    badge: '3A · PARALLEL',
    title: 'BM25 Keyword Scoring',
    sub: 'Worker thread · non-blocking',
    color: '#b45309',
    gradient: 'linear-gradient(135deg,#b45309,#c2410c)',
    iconKey: 'search',
    points: [
      'Probabilistic keyword relevance over all 180 candidates',
      'Dedicated Node.js worker — never blocks event loop',
    ],
  },
  {
    badge: '3B · PARALLEL',
    title: 'MiniLM Embeddings',
    sub: 'all-MiniLM-L6-v2 · ONNX in-process',
    color: '#059669',
    gradient: 'linear-gradient(135deg,#059669,#0d9488)',
    iconKey: 'layers',
    points: [
      'Semantic similarity via all-MiniLM-L6-v2 ONNX',
      '@xenova/transformers — lazy-loaded, cached in memory',
    ],
  },
];

export const STAGES = [
  {
    badge: 'Stage 1',
    title: 'Query Expansion',
    sub: 'Llama 3.3 70B · MeSH Vocabulary',
    color: '#7c3aed',
    gradient: 'linear-gradient(135deg,#7c3aed,#9333ea)',
    iconKey: 'sparkles',
    points: [
      '4 semantic query variants generated by Llama 3.3 70B',
      'MeSH mapping: "Parkinson\'s" → "Parkinson Disease"[MeSH]',
      'Synonym expansion (immunotherapy → PD-L1, nivolumab) · MeSH fallback',
    ],
  },
  {
    badge: 'Stage 3C',
    title: 'RRF Fusion',
    sub: 'Reciprocal Rank Fusion',
    color: '#db2777',
    gradient: 'linear-gradient(135deg,#db2777,#e11d48)',
    iconKey: 'merge',
    points: [
      'BM25 + semantic embeddings + recency + citation count merged',
      'Reciprocal Rank Fusion — no single signal dominates the result',
    ],
  },
  {
    badge: 'Stage 3D',
    title: 'Cross-Encoder Re-ranking',
    sub: 'ms-marco-MiniLM-L-6-v2',
    color: '#4f46e5',
    gradient: 'linear-gradient(135deg,#4f46e5,#2563eb)',
    iconKey: 'sliders',
    points: [
      'Reads query + document jointly for full context understanding',
      'More precise than bi-encoder similarity alone',
    ],
  },
  {
    badge: 'Stage 4',
    title: 'LLM Reasoning — Llama 3.3 70B',
    sub: 'Groq Cloud · strict anti-hallucination',
    color: '#9333ea',
    gradient: 'linear-gradient(135deg,#9333ea,#7c3aed)',
    iconKey: 'brain',
    points: [
      'Every claim must cite a real paper from context — zero hallucinations',
      'Evidence grading: Grade A (RCTs) → B (cohort) → C (expert opinion)',
      'Structured JSON: overview · findings · treatments · recommendations',
    ],
  },
  {
    badge: 'Output',
    title: 'Cited, Evidence-Graded Answer',
    sub: 'SSE stream → React frontend',
    color: '#16a34a',
    gradient: 'linear-gradient(135deg,#16a34a,#059669)',
    iconKey: 'check',
    points: [
      'Citation index validation strips any hallucinated references',
      'SSE stream delivers the full structured answer in under 15 seconds',
    ],
  },
];
