import logger from '../../utils/logger.js';

const PLACEHOLDER_PATTERNS = [
  /\bX\s*%/,
  /\bY\s+months?\b/i,
  /\bZ\s+patients?\b/i,
  /\b[XYZ]\s*%\s*(?:improvement|reduction|increase|decrease)/i,
  /improvement observed at [A-Z] months/i,
  /\bA\s+vs\s+B\b/i,
];

function hasPlaceholder(text) {
  return PLACEHOLDER_PATTERNS.some((re) => re.test(text));
}

function stripPlaceholderLeaks(arr) {
  if (!Array.isArray(arr)) return arr;
  const cleaned = arr.filter((item) => {
    const text = typeof item === 'string' ? item : (item?.text || JSON.stringify(item));
    const leaked = hasPlaceholder(text);
    if (leaked) logger.warn(`[Formatter] Stripped placeholder leak: "${text.slice(0, 80)}"`);
    return !leaked;
  });
  return cleaned;
}

function objectToString(obj) {
  if (typeof obj === 'string') return obj;
  if (typeof obj !== 'object' || obj === null) return String(obj);
  for (const key of ['text', 'summary', 'content', 'description', 'value', 'recommendation']) {
    if (typeof obj[key] === 'string' && obj[key].trim()) return obj[key];
  }
  const parts = Object.values(obj).filter((v) => typeof v === 'string' && v.trim());
  if (parts.length > 0) return parts.join(' ');
  return JSON.stringify(obj);
}

function toStringArray(val) {
  if (!val) return [];
  if (Array.isArray(val)) {
    return val.map((s) => {
      if (typeof s === 'string') return s.trim() ? s : null;
      if (typeof s === 'object' && s !== null) return objectToString(s);
      return null;
    }).filter(Boolean);
  }
  if (typeof val === 'string' && val.trim()) return [val];
  if (typeof val === 'object' && val !== null) return [objectToString(val)];
  return [];
}

function coerceToString(val) {
  if (!val) return '';
  if (typeof val === 'string') return val;
  if (Array.isArray(val)) return val.map((i) => (typeof i === 'string' ? i : objectToString(i))).join(' ');
  if (typeof val === 'object') return objectToString(val);
  return String(val);
}

export function extractJSONFromLLM(rawString) {
  if (!rawString) return null;

  try {
    return JSON.parse(rawString);
  } catch {
    logger.debug('Direct JSON parse failed, attempting extraction...');
  }

  try {
    const jsonMatch = rawString.match(/```json\s*([\s\S]*?)\s*```/i) ||
                      rawString.match(/```\s*(\{[\s\S]*?\})\s*```/);
    if (jsonMatch && jsonMatch[1]) return JSON.parse(jsonMatch[1]);
  } catch {
    logger.debug('Markdown JSON parse failed.');
  }

  try {
    const startIdx = rawString.indexOf('{');
    const endIdx   = rawString.lastIndexOf('}');
    if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
      return JSON.parse(rawString.substring(startIdx, endIdx + 1));
    }
  } catch {
    logger.warn('Regex JSON extraction failed entirely.');
  }

  return null;
}

export function ensureSchema(parsedObj, rawString) {
  if (parsedObj) {

    if (parsedObj.focused_answer) {
      const fa = parsedObj.focused_answer;
      return {
        conditionOverview:    coerceToString(parsedObj.condition_overview || parsedObj.conditionOverview || ''),
        keyFindings:          stripPlaceholderLeaks(toStringArray(fa.key_findings)),
        treatmentAnalysis:    [],
        researchInsights:     [],
        outcomesSummary:      [],
        limitations:          [],
        clinicalTrialsSummary: '',
        contradictions:       null,
        recommendation:       coerceToString(fa.disease_specific_evidence || fa.direct_answer || ''),
        confidenceLabel:      null,
        topResearchers:       Array.isArray(fa.researchers) ? fa.researchers : [],
        focused_answer:       fa,
        showOnlyFocused:      true,
        disclaimer:           coerceToString(parsedObj.disclaimer || 'Information generated by AI. Consult a doctor.'),
      };
    }

    const conditionOverview = coerceToString(
      parsedObj.condition_overview || parsedObj.conditionOverview,
    );

    const keyFindings      = stripPlaceholderLeaks(toStringArray(parsedObj.key_findings));
    const treatmentAnalysis = stripPlaceholderLeaks(toStringArray(parsedObj.treatment_analysis));
    const outcomesSummary   = stripPlaceholderLeaks(
      toStringArray(parsedObj.outcomes_summary || parsedObj.outcomesSummary),
    );

    const researchInsights = (Array.isArray(parsedObj.researchInsights) ? parsedObj.researchInsights : [])
      .map((ins) => ({
        insight:          ins.insight || '',
        citation:         ins.citation || '',
        evidenceStrength: ins.evidenceStrength || 'Not specified',
        relevance:        ins.relevance || '',
      }));

    const limitationsRaw = parsedObj.limitations;
    const limitations = Array.isArray(limitationsRaw)
      ? limitationsRaw.filter((s) => typeof s === 'string' && s.trim())
      : (typeof limitationsRaw === 'string' && limitationsRaw.trim() ? [limitationsRaw] : []);

    const rawCTS = parsedObj.clinical_trials_summary || parsedObj.clinicalTrialsInsights;
    const clinicalTrialsSummary = coerceToString(rawCTS);

    const contradictions = parsedObj.contradictions || null;

    const recommendation = coerceToString(
      parsedObj.personalized_recommendation || parsedObj.recommendation,
    );

    const confidenceLabel = coerceToString(
      parsedObj.confidence || parsedObj.confidenceLabel,
    ) || null;

    const llmResearchers = Array.isArray(parsedObj.topResearchers)
      ? parsedObj.topResearchers.map((r) => ({
          name:           r.name || '',
          paperCount:     r.paperCount || 0,
          totalCitations: r.totalCitations || 0,
          topPaper:       r.topPaper || '',
          note:           r.note || '',
        })).filter((r) => r.name)
      : [];

    const evidenceGrade = parsedObj.evidence_grade ?? null;

    return {
      conditionOverview,
      keyFindings,
      treatmentAnalysis,
      researchInsights,
      outcomesSummary,
      limitations,
      clinicalTrialsSummary,
      contradictions,
      recommendation,
      confidenceLabel,
      evidenceGrade,
      topResearchers:  llmResearchers,
      showOnlyFocused: false,
      disclaimer: parsedObj.disclaimer || 'Information generated by AI. Consult a doctor.',
    };
  }

  return {
    conditionOverview:    'We encountered an error structuring the response.',
    keyFindings:          [],
    treatmentAnalysis:    [],
    researchInsights:     [],
    outcomesSummary:      [],
    limitations:          [],
    clinicalTrialsSummary: '',
    contradictions:       null,
    recommendation:       rawString || 'No text generated.',
    confidenceLabel:      null,
    topResearchers:       [],
    showOnlyFocused:      false,
    disclaimer:           'Warning: Unstructured AI response fallback triggered.',
  };
}
